name: Playwright Tests
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Create .env file
      run:
        touch .env
        echo "LOGIN_NAME=${{ secrets.LOGIN_NAME }}" >> .env
        echo "PASSWORD=${{ secrets.PASSWORD }}" >> .env
        echo "EMAIL=${{ secrets.EMAIL }}" >> .env
        echo "LAST_NAME=${{ secrets.LAST_NAME }}" >> .env
        echo "FIRST_NAME=${{ secrets.FIRST_NAME }}" >> .env
        echo "API_TOKEN=${{ secrets.API_TOKEN }}" >> .env
        echo "PROJECT_CODE=${{ secrets.PROJECT_CODE }}" >> .env
    - name: Download auth.json from Google Drive
      run: wget --no-check-certificate "https://drive.google.com/uc?export=download&id=1MZ0yC0qrbN506-B_P8lsyXAjK0x8_64R" -O auth.json
    - name: Run Playwright test login
      run: yarn playwright test login.ts
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30